version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app-2810"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-qsxax86vu1fh"
s3_prefix = "sam-app-2810"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
