AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  REST_To-Do_List

  Sample SAM Template for REST_To-Do_List
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: nodejs16.x
    Timeout: 3
    Tracing: Active
  Api:
    TracingEnabled: True

Resources:
# DynamoDB Table
  itemsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: ItemID
        Type: Number

      TableName: Items
  
  readAllItemsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: to-do_list/
      Handler: readAllItems.handler
      # Runtime: nodejs16.x
      Role: arn:aws:iam::998203903345:role/LabRole
      Architectures:
        - x86_64
      Events:
        readItem:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /list/readAll
            Method: get

  readOneItemFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: to-do_list/
      Handler: readOneItem.handler
      # Runtime: nodejs16.x
      Role: arn:aws:iam::998203903345:role/LabRole
      Architectures:
        - x86_64
      Events:
        readItem:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /list/readOne
            Method: get
  
  updateItemFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: to-do_list/
      Handler: updateItem.handler
      # Runtime: nodejs16.x
      Role: arn:aws:iam::998203903345:role/LabRole
      Architectures:
        - x86_64
      Events:
        UpdateItem:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /list/update
            Method: put

  deleteItemFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: to-do_list/
      Handler: deleteItem.handler
      # Runtime: nodejs16.x
      Role: arn:aws:iam::998203903345:role/LabRole
      Architectures:
        - x86_64
      Events:
        DeleteItem:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /list/delete
            Method: delete

  createItemFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: to-do_list/
      Handler: createItem.handler
      # Runtime: nodejs16.x
      Role: arn:aws:iam::998203903345:role/LabRole
      Architectures:
        - x86_64
      Events:
        CreateItem:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /list/create
            Method: post

# Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  # HelloWorldApi:
  #   Description: "API Gateway endpoint URL for Prod stage for Hello World function"
  #   Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  # # HelloWorldFunction:
  #   Description: "Hello World Lambda Function ARN"
  #   Value: !GetAtt HelloWorldFunction.Arn
