AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  REST_To-Do_List

  Sample SAM Template for REST_To-Do_List
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: nodejs16.x
    Timeout: 3
    Tracing: Active
  Api:
    TracingEnabled: True

Resources:
# DynamoDB Table
  ItemsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: ItemID
        Type: Number
      TableName: Items

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: API
      EndpointConfiguration:
        Type: REGIONAL
      Cors:
        AllowMethods: "'POST, GET, DELETE, PUT, OPTIONS'"
        AllowHeaders: "'Content-Type, X-Amz-Date, Authentication, Authorization, X-Api-Key, X-Amz-Security-Token'"
        AllowOrigin: "'*'"
  
  ReadAllItemsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: to-do_list/
      Handler: readAllItems.handler
      # Runtime: nodejs16.x
      Role: arn:aws:iam::998203903345:role/LabRole
      Architectures:
        - x86_64
      Events:
        readItem:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /items/readAll
            Method: get
            RestApiId: !Ref ApiGateway
        # options:
        #   Type: Api
        #   Properties:
        #     Path: /items/readAll
        #     Method: options
        #     RestApiId: !Ref ApiGateway

  ReadOneItemFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: to-do_list/
      Handler: readOneItem.handler
      # Runtime: nodejs16.x
      Role: arn:aws:iam::998203903345:role/LabRole
      Architectures:
        - x86_64
      Events:
        readItem:
          Type: Api
          Properties:
            Path: /items/readOne
            Method: get
            RestApiId: !Ref ApiGateway
        # options:
        #   Type: Api
        #   Properties:
        #     Path: /items/readOne
        #     Method: options
        #     RestApiId: !Ref ApiGateway
  
  UpdateItemFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: to-do_list/
      Handler: updateItem.handler
      # Runtime: nodejs16.x
      Role: arn:aws:iam::998203903345:role/LabRole
      Architectures:
        - x86_64
      Events:
        UpdateItem:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /items/update
            Method: put
            RestApiId: !Ref ApiGateway
        # options:
        #   Type: Api
        #   Properties:
        #     Path: /items/update
        #     Method: OPTIONS
        #     RestApiId: !Ref ApiGateway

  DeleteItemFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: to-do_list/
      Handler: deleteItem.handler
      # Runtime: nodejs16.x
      Role: arn:aws:iam::998203903345:role/LabRole
      Architectures:
        - x86_64
      Events:
        DeleteItem:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /items/delete
            Method: delete
            RestApiId: !Ref ApiGateway
        # options:
        #   Type: Api
        #   Properties:
        #     Path: /items/delete
        #     Method: OPTIONS
        #     RestApiId: !Ref ApiGateway

  CreateItemFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: to-do_list/
      Handler: createItem.handler
      # Runtime: nodejs16.x
      Role: arn:aws:iam::998203903345:role/LabRole
      Architectures:
        - x86_64
      Events:
        CreateItem:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /items/create
            Method: post
            RestApiId: !Ref ApiGateway
        # options:
        #   Type: Api
        #   Properties:
        #     Path: /items/create
        #     Method: OPTIONS
        #     RestApiId: !Ref ApiGateway

# Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  # HelloWorldApi:
  #   Description: "API Gateway endpoint URL for Prod stage for Hello World function"
  #   Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  # # HelloWorldFunction:
  #   Description: "Hello World Lambda Function ARN"
  #   Value: !GetAtt HelloWorldFunction.Arn
